[build-system]
  build-backend = "uv_build"
  requires      = ["uv_build>=0.10.3,<0.11.0"]

[tool.uv.build-backend]
  module-name = "aardvark"
  module-root = ""

[project]
  authors = [{email = "conrad@conradhaupt.com", name = "Conrad Haupt"}]
  classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python",
    "Topic :: Database",
    "Topic :: File Formats",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Libraries",
  ]
  dependencies = [
    "PyYAML>=6.0.2",                             # Require PyYaml versions that support 3.13
    "asdf-qiskit~=0.1",
    "asdf>=5.0.0",
    "jsonschema~=4.24",
    "matplotlib>=3.9.4",
    "typing_extensions; python_version<='3.10'",
  ]
  description = "Manage experiments and associated \"aard\"ifacts easily, and without having to worry about Pickle."
  license = {file = "LICENSE.txt"}
  maintainers = [{email = "conrad@conradhaupt.com", name = "Conrad Haupt"}]
  name = "aardvark"
  readme = "README.md"
  requires-python = ">=3.10"
  version = "0.1.4"

[dependency-groups]
  dev = [
    "ddt==1.7.2",
    "furo",
    "pytest",
    "pytest-asdf-plugin",
    "pytest-benchmark~=5.1",
    "pytest-cov",
    "reno>=4.1.0",
    "ruff",
    "sphinx",
    "sphinx-asdf",
    "sphinx_design",
]
  docs = ["furo", "sphinx", "sphinx-asdf", "sphinx_design"]
  tests = ["ddt==1.7.2", "pytest", "pytest-asdf-plugin", "pytest-benchmark~=5.1", "pytest-cov", "ruff"]

[project.urls]
  Documentation = "https://github.com/conradhaupt/aardvark#readme"
  Issues        = "https://github.com/conradhaupt/aardvark/issues"
  Source        = "https://github.com/conradhaupt/aardvark/tree/main/aardvark"

[project.entry-points]
  "asdf.extensions"        = {aardvark = 'aardvark.asdf.extension:get_extensions'}
  "asdf.resource_mappings" = {aardvark = 'aardvark.resources:get_resource_mappings'}


[tool.pytest.ini_options]
  addopts                   = "-W error"
  asdf_schema_root          = 'aardvark/resources/schemas/'
  asdf_schema_tests_enabled = 'true'

[tool.pyright]
  # Target 3.10, the minimum version we support.
  pythonVersion          = "3.10"
  reportMissingTypeStubs = false
  typeCheckingMode       = "basic"

[tool.ruff.lint]
  preview = true
  select = [
    # Rules in alphabetic order
    "C4",     # category: flake8-comprehensions
    "CPY001", # missing-copyright-notice (see flake8-copyright setting)
    "EXE",    # Category: flake8-executable
    "F631",   # assert-tuple
    "F632",   # is-literal
    "F634",   # if-tuple
    "F823",   # undefined-local
    "G",      # flake8-logging-format
    "T10",    # category: flake8-debugger
  ]

[tool.ruff.lint.flake8-copyright]
  author = "Conrad Haupt <conrad@conradhaupt.com> and IBM"
