[tox]
envlist =
    test-py3{10-14}
    save-py3{10-14}-{0_1}
    load-py3{10-14}-{0_1}
    lint
    coverage
skipsdist = false

[testenv]
install_command = pip install -U {opts:} {packages:}
deps =
    pytest
    pytest-asdf-plugin
    ddt==1.7.2
setenv =
    PYTHONPATH = {toxinidir}
    py310: PYTHON_VERSION = 3.10
    py311: PYTHON_VERSION = 3.11
    py312: PYTHON_VERSION = 3.12
    py313: PYTHON_VERSION = 3.13
    py314: PYTHON_VERSION = 3.14

    0_1: AARDVARK_VERSION = 0.1

[testenv:test-py3{10-14}]
description = "Unit tests"
commands = 
    pytest tests

[testenv:save-py3{10-14}-{0_1}]
description = "Compatibility tests, first stage where data is saved to ASDF files."
package = skip
commands_pre =
    python -m pip install "aardvark @ git+https://github.com/conradhaupt/expres.git@release/{env:AARDVARK_VERSION}"
commands =
    pytest --quiet -p pytest_aardvark_fixtures \
        --aardvark-fixtures-save \
        --aardvark-fixtures-overwrite \
        --aardvark-fixtures-dir=.pytest_aardvark_fixtures/py{env:PYTHON_VERSION}_{env:AARDVARK_VERSION} \
        compatibility_tests

[testenv:load-py3{10-14}-{0_1}]
description = "Compatibility tests, second stage where data is loaded from ASDF files."
commands =
    pytest -p pytest_aardvark_fixtures \
    --asdf-fixtures-load \
    ; Aardvark version 0.1
    --asdf-fixtures-dir=.pytest_aardvark_fixtures/py3.10_0.1 \
    --asdf-fixtures-dir=.pytest_aardvark_fixtures/py3.11_0.1 \
    --asdf-fixtures-dir=.pytest_aardvark_fixtures/py3.12_0.1 \
    --asdf-fixtures-dir=.pytest_aardvark_fixtures/py3.13_0.1 \
    compatibility_tests


[testenv:benchmark]
description = "Benchmark some critical functions and their implementations."
basepython = python3
deps = 
    {[testenv]deps}
    pytest-benchmark
commands = 
    pytest --benchmark-warmup=on \
      --benchmark-save-data \
      --benchmark-autosave \
      --benchmark-min-rounds=5 \
      benchmarks

[testenv:lint]
description = "Run ruff and license header linting."
deps =
    ruff
commands = 
    ruff check aardvark tests
    python ./tools/verify_headers.py aardvark tests

[testenv:coverage]
description = "Compute coverage over all unit-tests with pytest-cov."
deps = 
    pytest
    pytest-cov
    pytest-asdf-plugin
    ddt==1.7.2
commands = 
    pytest --cov aardvark --cov-config=.coveragerc tests
