[tox]
envlist =
    test-py3{10-14},lint,coverage
skipsdist = false

[testenv]
install_command = pip install -U {opts:} {packages:}
deps =
    pytest
    pytest-asdf-plugin
    ddt==1.7.2

[testenv:test-py3{10-14}]
description = "Unit tests"
commands = 
    pytest tests

[testenv:benchmark]
description = "Benchmark some critical functions and their implementations."
basepython = python3
deps = 
    {[testenv]deps}
    pytest-benchmark
commands = 
    pytest --benchmark-warmup=on \
      --benchmark-save-data \
      --benchmark-autosave \
      --benchmark-min-rounds=5 \
      benchmarks

[testenv:lint]
description = "Run ruff and license header linting."
deps =
    ruff
commands = 
    ruff check aardvark tests
    python ./tools/verify_headers.py aardvark tests

[testenv:coverage]
description = "Compute coverage over all unit-tests with pytest-cov."
deps = 
    pytest
    pytest-cov
    pytest-asdf-plugin
    ddt==1.7.2
commands = 
    pytest --cov aardvark --cov-config=.coveragerc tests
